version: "3.8"
services:
  nginx:
    image: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - type: bind
      source: ./nginx/conf.d
      target: /etc/nginx/conf.d/
    - type: bind
      source: ./nginx/cert
      target: /webblog/cert
    depends_on:
      - app
  db:
    image: mysql
    volumes:
    - type: volume
      source: db_webblog
      target: /var/lib/mysql
    env_file:
      - .env
  app:
    build:
      context: .
    environment:
      WEBAPP_ENV: Prod
      OAUTHLIB_INSECURE_TRANSPORT: 1
    env_file:
      - .env
    depends_on:
      - db
volumes:
  db_webblog:

