version: "3.8"
services:
  nginx:
    image: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - type: bind
      source: ./nginx/conf.d
      target: /etc/nginx/conf.d/
    - type: bind
      source: ./nginx/cert
      target: /webblog/cert
    - type: bind
      source: ./nginx/dhparam
      target: /webblog/dhparam
    depends_on:
      - app
  db:
    image: mysql
    ports:
    - "3306:3306"
    volumes:
    - type: volume
      source: db_webblog
      target: /var/lib/mysql
    env_file:
      - .env
  redis:
    image: redis
    ports:
    - "6379:6379"
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - .env
  worker:
    build:
      context: .
      dockerfile: Dockerfile_worker
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
  app:
    build:
      context: .
    environment:
      WEBAPP_ENV: Prod
      OAUTHLIB_INSECURE_TRANSPORT: 1
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
      - redis

volumes:
  db_webblog:

