version: "3.8"
services:
  db:
    image: mysql
    volumes:
    - type: volume
      source: db_webblog
      target: /var/lib/mysql
    ports:
    - "3306:3306"
    env_file:
      - .env
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
  app:
    build:
      context: .
    ports:
    - "80:5000"
    env_file:
      - .env
volumes:
  db_webblog:

